### Fetch All raw materials
GET http://localhost:9300/rawMaterialOrder

### POST 
POST http://localhost:9300/rawMaterialOrder

### Fetch Valid RawMaterial Order
GET http://localhost:9300/rawMaterialOrder/1000004

### Fetch In Valid RawMaterial Order
GET http://localhost:9300/rawMaterialOrder/1000999

### Update Order Status - Already delivered
PUT http://localhost:9300/rawMaterialOrder
Content-Type: application/json

{
  "orderId": "1000000",
  "status": "Delivered"
}

### Update Order Status - Already cancelled
PUT http://localhost:9300/rawMaterialOrder
Content-Type: application/json

{
  "orderId": "1000002",
  "status": "Delivered"
}

### Update Order Status - Makes order quantity of 1000001 as 70 to 125
PUT http://localhost:9300/rawMaterialOrder
Content-Type: application/json

{
  "orderId": "1000003",
  "status": "Delivered"
}

### Insert RawMaterial Order - Missing data
POST  http://localhost:9300/rawMaterialOrder
Content-Type: application/json

{
  "rawMaterialId": "10000000",
  "pricePerUnit": 56,
  "qualityCheck": "Passe",
  "deliveryDate": "2020-11-03",
  "expiryDate": "2022-11-03",
  "supplierId": "1000000"
}

### Insert RawMaterial Order  - Invalid Data
POST  http://localhost:9300/rawMaterialOrder
Content-Type: application/json

{
  "rawMaterialId": "10000000",
  "quantity": "44",
  "pricePerUnit": 56,
  "qualityCheck": "Passe",
  "deliveryDate": "2020-11-03",
  "expiryDate": "2022-11-03",
  "supplierId": "1000000"
}

### Insert RawMaterial Order  - Past date
POST  http://localhost:9300/rawMaterialOrder
Content-Type: application/json

{
  "rawMaterialId": "10000000",
  "quantity": "44",
  "pricePerUnit": 56,
  "qualityCheck": "Passe",
  "deliveryDate": "2020-11-03",
  "expiryDate": "2019-11-03",
  "supplierId": "1000000"
}

### Insert RawMaterial Order  - Valid Data
POST  http://localhost:9300/rawMaterialOrder
Content-Type: application/json

{
  "rawMaterialId": "1000000",
  "quantity": "44",
  "pricePerUnit": 56,
  "qualityCheck": "Passed",
  "deliveryDate": "2020-11-03",
  "expiryDate": "2022-11-03",
  "supplierId": "1000000"
}
