apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gagandeep39/inventory-gateway-server
          resources:
            limits:
              memory: '350Mi'
              cpu: '250m'
          env:
            - name: eureka.instance.preferIpAddress
              value: 'true'
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: eureka.client.serviceurl.defaultzone
              value: http://inventory-discovery-server:8761/eureka
            - name: spring.datasource.url
              value: jdbc:h2:tcp://inventory-database-service:9550/~/test
            - name: ribbon.ReadTimeout
              value: '60000'

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-gateway-cluster-srv
spec:
  selector:
    app: gateway
  ports:
    - name: gateway-srv-clusterip-port
      protocol: TCP
      port: 9000
      targetPort: 9000


---
# Redundant for Current deployment
apiVersion: v1
kind: Service
metadata:
  name: gateway-srv
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - port: 9000 # Node service port
      name: gateway-port
      protocol: TCP
      targetPort: 9000 # Port of pod we want to expose
      nodePort: 30005
