# Run below command before this
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.40.2/deploy/static/provider/cloud/deploy.yaml

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    # Make sure to redirect post.com to localhost at C:\Windows\System32\drivers\etc\hosts for testing
    # Post service can now be accessed frm localhost/posts
    - http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: inventory-gateway-cluster-srv
              servicePort: 9000
