apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-management-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-management
  template:
    metadata:
      labels:
        app: stock-management
    spec:
      containers:
        - name: stock-management
          image: gagandeep39/inventory-stock-management-service
          resources:
            limits:
              memory: '300Mi'
              cpu: '250m'
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: eureka.client.serviceurl.defaultzone
              value: http://inventory-discovery-server:8761/eureka
            - name: spring.datasource.url
              value: jdbc:h2:tcp://inventory-database-service:9550/~/test
            - name: eureka.instance.preferIpAddress
              value: 'true'

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-stock-management-service
spec:
  selector:
    app: stock-management
  ports:
    - name: stock-management-srv-clusterip-port
      protocol: TCP
      port: 9400
      targetPort: 9400
