spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level:
    ROOT: info
    com.cg: info
# Disables discovery CLient eatures - Use this or Confi file
eureka:
  client:
    enabled: true
