server:
  port: ${server_port:9100}
spring:
  profiles:
    active: dev
  application:
    name: inventory-auth-service
eureka:
  client:
    serviceUrl:
      # Changed because previous once was ausing errors with gateway
      defaultZone: ${eureka_url:http://localhost:8761/eureka/}

# JTW Config
jwt:
  secret: ${jwt_secret:thisisathirtycharacterlongstring}
  expiration: 3600000
