spring:
  aop:
    auto: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:tcp://localhost:9550/mem:mydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    # Info level for all java logs
    ROOT: info
    # debug leavel for all user defined classes log
    com.cg: info
# Enable discovery CLient eatures - Use this or Confi file
eureka:
  client:
    enabled: true
