server:
  port: ${server_port:9300}
spring:
  profiles:
    active: dev
  application:
    name: inventory-rawmaterial-order-service
eureka:
  client:
    serviceUrl:
      # Changed because previous once was ausing errors with gateway
      defaultZone: ${eureka_url:http://localhost:8761/eureka/}
