server:
  port: ${server_port:9200}
spring:
  profiles:
    active: mysql
  application:
    name: inventory-product-order-service
eureka:
  client:
    serviceUrl:
      # Changed because previous once was ausing errors with gateway
      defaultZone: ${eureka_url:http://localhost:8761/eureka/}
