name: Deploy to AWS S3

on:
  push:
    branches:
      - dev
    paths:
      - 'inventory-frontend/**'

defaults:
  run:
    working-directory: inventory-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Make a production build
        run: |
          npm install -g @angular/cli@latest
          npm install
          ng build --prod
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2' # optional: defaults to us-east-1
          SOURCE_DIR: 'inventory-frontend/dist/inventory-frontend' # optional: defaults to entire repository
